language: java

services:
  - docker

script:
  - ./gradlew build --scan -s
  - ./gradlew check

after_success:
  - docker build -t villanelle/vitanum-naming-server .
  - docker push villanelle/vitanum-naming-server:$RELEASE

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
