#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

docker build -t "$DOCKER_USERNAME"/vitanum-naming-server .
docker push "$DOCKER_USERNAME"/vitanum-naming-server:"$RELEASE"
